/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.pallavjain01;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PixelPaletteTest {
    @Test void appHasAGreeting() {
        PixelPalette classUnderTest = new PixelPalette();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
